runtime: nodejs18
env: standard
service: default

#Add the service account here
service_account: cookaing-da7d0@appspot.gserviceaccount.com

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10